// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/11/2024, 17:43:26
const configMerger = require("C:/portfolioJana/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/portfolioJana/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/portfolioJana/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/portfolioJana/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/portfolioJana/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/portfolioJana/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/portfolioJana/plugins/**/*.{js,ts,mjs}","C:/portfolioJana/composables/**/*.{js,ts,mjs}","C:/portfolioJana/utils/**/*.{js,ts,mjs}","C:/portfolioJana/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/portfolioJana/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/portfolioJana/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "C:/portfolioJana/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
